name: Build on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Etapa 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Etapa 2: Instalar MinGW
      - name: Install MinGW
        run: choco install mingw -y

      # Etapa 3: Verificar se mingw32-make está acessível
      - name: Verify mingw32-make
        run: |
          gcc --version
          mingw32-make --version

      # Etapa 4: Compilar o projeto
      - name: Build project
        run: mingw32-make